"""Add daily_yield to assemblies

Revision ID: 08dcac638fdb
Revises: 7a0f8b8c1c2a
Create Date: 2026-06-02 22:02:59.765780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08dcac638fdb'
down_revision: Union[str, None] = '7a0f8b8c1c2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assemblies', sa.Column('daily_yield', sa.Float(), nullable=True))
    op.drop_constraint(op.f('assemblies_name_key'), 'assemblies', type_='unique')
    op.drop_constraint(op.f('materials_name_key'), 'materials', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('materials_name_key'), 'materials', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('assemblies_name_key'), 'assemblies', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('assemblies', 'daily_yield')
    # ### end Alembic commands ###
