"""add_deleted_pages_to_plans

Revision ID: 10f9d8c61f03
Revises: fc11ee62877f
Create Date: 2026-05-21 22:55:03.763106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '10f9d8c61f03'
down_revision: Union[str, None] = 'fc11ee62877f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('deleted_pages', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'deleted_pages')
    # ### end Alembic commands ###
