"""add_materials_and_yields

Revision ID: 1fc6c0fbe443
Revises: 10f9d8c61f03
Create Date: 2026-05-22 19:03:38.169056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1fc6c0fbe443'
down_revision: Union[str, None] = '10f9d8c61f03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('material_yields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('applies_to', sa.String(length=32), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=False),
    sa.Column('waste_factor', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('element_materials',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['detected_elements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('element_id', 'material_id')
    )
    # ### end Alembic commands ###

    # Seed data
    materials_table = sa.table(
        'materials',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('category', sa.String),
        sa.column('unit', sa.String),
    )
    yields_table = sa.table(
        'material_yields',
        sa.column('id', sa.Integer),
        sa.column('material_id', sa.Integer),
        sa.column('applies_to', sa.String),
        sa.column('consumption', sa.Float),
        sa.column('waste_factor', sa.Float),
        sa.column('unit_price', sa.Float),
    )

    op.bulk_insert(materials_table, [
        {'id': 1, 'name': 'Ladrillo Hueco 18x18x33', 'category': 'Mampostería', 'unit': 'un'},
        {'id': 2, 'name': 'Pintura Látex Interior', 'category': 'Pinturas', 'unit': 'l'},
        {'id': 3, 'name': 'Porcelanato 60x60', 'category': 'Pisos', 'unit': 'm2'},
        {'id': 4, 'name': 'Zócalo de Madera', 'category': 'Zócalos', 'unit': 'ml'},
    ])

    op.bulk_insert(yields_table, [
        {'id': 1, 'material_id': 1, 'applies_to': 'wall', 'consumption': 15.0, 'waste_factor': 0.05, 'unit_price': 0.0},
        {'id': 2, 'material_id': 2, 'applies_to': 'room_wall', 'consumption': 0.20, 'waste_factor': 0.08, 'unit_price': 0.0},
        {'id': 3, 'material_id': 3, 'applies_to': 'room_floor', 'consumption': 1.0, 'waste_factor': 0.10, 'unit_price': 0.0},
        {'id': 4, 'material_id': 4, 'applies_to': 'room_perimeter', 'consumption': 1.0, 'waste_factor': 0.07, 'unit_price': 0.0},
    ])

    op.execute("SELECT setval('materials_id_seq', (SELECT MAX(id) FROM materials))")
    op.execute("SELECT setval('material_yields_id_seq', (SELECT MAX(id) FROM material_yields))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('element_materials')
    op.drop_table('material_yields')
    op.drop_table('materials')
    # ### end Alembic commands ###
