"""Add BYOK AI Provider fields and PlanAiContext

Revision ID: 5539a7e60576
Revises: 08dcac638fdb
Create Date: 2026-06-10 19:55:12.130538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5539a7e60576'
down_revision: Union[str, None] = '08dcac638fdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_ai_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id')
    )
    op.add_column('organizations', sa.Column('ai_provider', sa.String(length=64), server_default='scalist', nullable=False))
    op.add_column('organizations', sa.Column('ai_api_key', sa.String(length=1024), nullable=True))
    op.add_column('organizations', sa.Column('ai_model_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'ai_model_name')
    op.drop_column('organizations', 'ai_api_key')
    op.drop_column('organizations', 'ai_provider')
    op.drop_table('plan_ai_contexts')
    # ### end Alembic commands ###
