"""saas_and_assemblies

Revision ID: 600324646bb1
Revises: 0008_project_training_consent
Create Date: 2026-06-01 23:50:04.289885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '600324646bb1'
down_revision: Union[str, None] = '0008_project_training_consent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('applies_to', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assembly_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('consumption', sa.Float(), nullable=False),
    sa.Column('waste_factor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('element_assemblies',
    sa.Column('element_id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['element_id'], ['detected_elements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('element_id', 'assembly_id')
    )
    op.drop_table('element_materials')
    op.drop_table('material_yields')
    op.add_column('materials', sa.Column('unit_price', sa.Float(), server_default='0.0', nullable=False))
    op.execute("INSERT INTO organizations (id, name, subscription_status) VALUES (1, 'Default Organization', 'active') ON CONFLICT DO NOTHING")
    op.add_column('projects', sa.Column('organization_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('org_role', sa.String(length=32), server_default='admin', nullable=False))
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=32), server_default=sa.text("'director_obra'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'is_superadmin')
    op.drop_column('users', 'org_role')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'organization_id')
    op.drop_column('materials', 'unit_price')
    op.create_table('material_yields',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('applies_to', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('consumption', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('waste_factor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('material_yields_material_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('material_yields_pkey'))
    )
    op.create_table('element_materials',
    sa.Column('element_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['element_id'], ['detected_elements.id'], name=op.f('element_materials_element_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('element_materials_material_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('element_id', 'material_id', name=op.f('element_materials_pkey'))
    )
    op.drop_table('element_assemblies')
    op.drop_table('assembly_materials')
    op.drop_table('organizations')
    op.drop_table('assemblies')
    # ### end Alembic commands ###
